config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("", index),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

posts/urls.py
from django.urls import path
from posts.views import feeds

urlpatterns = [
    path("feeds/", feeds),
]

users/urls.py
from django.urls import path
from users.views import login_view, logout_view, signup

urlpatterns = [
    path('login/', login_view),
    path('logout/', logout_view),
    path('signup/', signup),
]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

class PostImage(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="포스트",
        on_delete=models.CASCADE,
    )
    photo = models.ImageField("사진", upload_to="post")

class Comment(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="작성자",
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(Post, verbose_name="포스트", on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("생성일시", auto_now_add=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    profile_image = models.ImageField(
        "프로필 이미지", upload_to="users/profile", blank=True)
    short_description = models.TextField("소개글", blank=True)

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from users.models import User

class LoginForm(forms.Form):
    userId = forms.CharField(
        min_length=3,
        widget=forms.TextInput(
            attrs={"placeholder": "전화번호, 사용자 이름 또는 이메일"}
        )
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호"},
        ),
    )
class SignupForm(forms.Form):
    userId = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "휴대폰 번호 또는 이메일 주소"}))
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "성명"}))
    nickname = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "사용자 이름"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "비밀번호"}))

    def cleam_userId(self):
        userId = self.cleaned_data["nickname"]
        if User.objects.filter(userId=userId).exists():
            raise ValidationError(f"입력한 사용자명 {{userId}}은 이미 사용 중입니다.")
        return userId

    def clean_password(self):
        password = self.cleaned_data["password"]
        if len(password) < 4:
            self.add_error("password", "비밀번호는 4자리 이상이어야 합니다.")

    def save(self):
        userId = self.cleaned_data["userId"]
        password = self.cleaned_data["password"]
        nickname = self.cleaned_data["nickname"]
        name = self.cleaned_data["name"]
        user = User.objects.create_user(
            userId=userId,
            password=password,
            username=nickname,
            name=name,
        )
        return user

config/views.py
from django.shortcuts import redirect

def index(request):
    # 로그인되어 있는 경우, 피드 페이지로 redirect
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")
    # 로그인되어 있지 않은 경우, 로그인 페이지로 redirect
    else:
        return redirect("/users/login/")

posts/views.py
from django.shortcuts import render, redirect
from posts.models import Post
# Create your views here.

def feeds(request):
    # 요청에 포함된 사용자가 로그인하지 않은 경우
    if not request.user.is_authenticated:
        #/users/login/ URL로 이동
        return redirect("/users/login/")

    # 모든 글 목록을 템플릿으로 전달
    posts = Post.objects.all()
    context = {"posts": posts}
    return render(request, 'posts/feeds.html', context)

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from users.forms import LoginForm, SignupForm
from users.models import User

# Create your views here.
def login_view(request):
    # 이미 로그인 되어 있다면
    if request.user.is_authenticated:
        return redirect("/posts/feeds/")

    if request.method == "POST":
        form = LoginForm(data=request.POST)
        # LoginForm에 전달된 데이터가 유효하다면
        if form.is_valid():
            # userId와 password 값을 가져와 변수에 할당
            userId = form.cleaned_data["userId"]
            password = form.cleaned_data["password"]

            # userId, password에 해당하는 사용자가 있는지 검사
            user = authenticate(userId=userId, password=password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 피드 페이지로 redirect
                login(request, user)
                return redirect("/posts/feeds/")
            # 사용자가 없다면 form에 에러 추가
            else:
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다")

        # 어떤 경우든 실패한 경우(데이터 검증, 사용자 검사) 다시 LoginForm을 사용한 로그인 페이지 랜더링
        context = {
            "form": form,
        }
        return render(request, 'users/login.html', context)
    else:
        form = LoginForm()
        context = {
            "form": form,
        }
        return render(request, 'users/login.html', context)

def logout_view(request):
    # logout 함수 호출에 request를 전달한다
    logout(request)

    # logout 처리 후, 로그인 페이지로 이동한다
    return redirect("/users/login/")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/posts/feeds/")

    else:
        form = SignupForm()

    context = {"form" : form}
    return render(request, 'users/signup.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'splide/splide.css' %}">
    <script src="{% static 'splide/splide.js' %}"></script>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/posts/feeds.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <nav>
        <img style="width: 200px"
                     src = "{% static 'img/images.png' %}">
    </nav>
    <div id="feeds" class="post-container">
        {% for post in posts %}
            <article class="post">
                <header class="post-header">
                    {% if post.user.profile_image %}
                        <img src="{{post.user.profile_image_url}}">
                    {% endif %}
                    <span>{{post.user.username}}</span>
                </header>

                <div class="post-images splide">
                    <div class="splide__track">
                        <ul class="splide__list">
                            {% for image in post.postimage_set.all %}
                                {% if image.photo %}
                                <li class ="splide__slide">
                                    <img src="{{ image.photo.url }}">
                                </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </article>
        {% endfor %}
    </div>

    <script>
        const elms = document.getElementsByClassName('splide')
        for(let i = 0; i < elms.length; i++) {
            new Splide(elms[i]).mount();
        }
    </script>
{% endblock %}

templates/users/login.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div id="login" style="padding: 20px; text-align: center; width: 100%">
        <img style="margin-right: 20px;"
                src="https://static.cdninstagram.com/images/instagram/xig/homepage/phones/home-phones.png?__makehaste_cache_breaker=HOgRclNOosk">
        <form method="POST">
            <img style="width: 200px"
                     src = "{% static 'img/images.png' %}">
            {% csrf_token %}
            <p>
                <label for="id_id"></label>
                <input type="text" name="username" placeholder="전화번호, 사용자 이름 또는 이메일" minlength="3" required id="id_id">
            </p>
            <p>
                <label for="id_password"></label>
                <input type="password" name="password" placeholder="비밀번호" minlength="4" required id="id_password">
            </p>
            <button type="submit" class="btn btn-login">로그인</button>
        </form>
    </div>

</body>
</html>

templates/users/signup.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
        <div id="signup" style="padding: 20px; text-align: center; width: 100%">
            <form method="POST" enctype="multipart/form-data">
                <div><img style="width: 200px"
                     src = "{% static 'img/images.png' %}"></div>
                <div style="font-weight: bold; color: gray; padding-bottom: 20px">친구들의 사진과 동영상을 보려면 가입하세요.</div>
                {% csrf_token %}
                <p>
                    <label for="id_userId"></label>
                    <input type="text" name="userId" placeholder="휴대폰 번호 또는 이메일 주소" required id="id_userId">
                </p>
                <p>
                    <label for="id_name"></label>
                    <input type="text" name="name" placeholder="성명" required id="id_name">
                </p>
                <p>
                    <label for="id_nickname"></label>
                    <input type="text" name="nickname" placeholder="사용자 이름" required id="id_nickname">
                </p>
                <p>
                    <label for="id_password"></label>
                    <input type="password" name="password" placeholder="비밀번호" required id="id_password">
                </p>
                <button type="submit" class="btn btn-signup">가입</button>
           </form>
        </div>
</body>
</html>